# Generated by Django 3.0.6 on 2020-05-28 14:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
