# Generated by Django 3.0.6 on 2020-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200528_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Обрабатывается'), ('Out of delivery', 'Доставка'), ('Delivered', 'Доставленно')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast ', 'Завтрак'), ('Lunch', 'Обед'), ('Dinner', 'Ужин')], max_length=200, null=True),
        ),
    ]
